# Generated by Django 3.0.5 on 2021-08-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_of_joining', models.DateField()),
                ('photo_file', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.Department')),
            ],
        ),
    ]
