# Generated by Django 3.0.5 on 2021-08-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Date_of_joining',
            new_name='date_of_joining',
        ),
    ]
