name: 🔂 Surge PR Preview

on:
  pull_request:
    # this insures preview would destroy after closing PR
    types: [opened, synchronize, reopened, closed]

jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client-nuxt

    steps:
      - uses: actions/checkout@v2
      # - run: cp .env.example .env
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: dist
          teardown: "true"
          build: |
            yarn
            yarn generate
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
